parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"AHCv":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"izif":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=s(require("@babel/runtime/helpers/defineProperty")),r=require("react"),t=require("react-router-dom"),o=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}class i extends r.Component{constructor(...r){super(...r),(0,e.default)(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(e,r){console.error("ErrorBoundary caught an error: ",e,r),setTimeout(()=>{this.setState({redirect:!0})},5e3)}render(){return this.state.redirect?(0,o.jsx)(t.Redirect,{to:"/"}):this.state.hasError?(0,o.jsxs)("h2",{children:["An error occured. ",(0,o.jsx)(t.Link,{to:"/",children:"Go back to the home page"})," or wait five seconds."]}):this.props.children}}var a=i;exports.default=a;
},{}],"q7Av":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=s(require("@babel/runtime/helpers/defineProperty")),t=require("react"),a=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}class r extends t.Component{constructor(...t){super(...t),(0,e.default)(this,"state",{active:0}),(0,e.default)(this,"handleClick",e=>{this.setState({active:parseInt(e.target.dataset.index)})})}render(){const{active:e}=this.state,{images:t}=this.props;return(0,a.jsxs)("div",{className:"carousel",children:[(0,a.jsx)("img",{src:t[e],alt:"animal"}),(0,a.jsx)("div",{className:"carousel-smaller",children:t.map((t,s)=>(0,a.jsx)("img",{src:t,"data-index":s,onClick:this.handleClick,className:s===e?"active":"",alt:"animal thumbnail"},t))})]})}}(0,e.default)(r,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=r;exports.default=i;
},{}],"SR9Y":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{const n=(0,e.useRef)(null);return u=u||document.getElementById("modal"),n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"5I+D":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=n(require("@babel/runtime/helpers/defineProperty")),t=require("react"),s=require("react-router-dom"),o=n(require("../contexts/ThemeContext")),i=n(require("../components/ErrorBoundary")),r=n(require("../components/Carousel")),a=n(require("../components/Modal")),d=require("react/jsx-runtime");function n(e){return e&&e.__esModule?e:{default:e}}class l extends t.Component{constructor(...t){super(...t),(0,e.default)(this,"state",{loading:!0,showModal:!1}),(0,e.default)(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),(0,e.default)(this,"adopt",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){const{animal:e,breed:t,city:s,state:i,images:n,description:l,name:c,showModal:u}=this.state;return this.state.loading?(0,d.jsx)("h2",{children:"Loading..."}):(0,d.jsxs)("div",{className:"details",children:[(0,d.jsx)(r.default,{images:n}),(0,d.jsxs)("div",{children:[(0,d.jsx)("h1",{children:c}),(0,d.jsxs)("h2",{children:[e," - ",t," - ",s,", ",i]}),(0,d.jsx)("p",{children:l}),(0,d.jsx)(o.default.Consumer,{children:([e])=>(0,d.jsxs)("button",{style:{backgroundColor:e},onClick:this.toggleModal,children:["Adopt ",c]})}),u?(0,d.jsx)(a.default,{children:(0,d.jsxs)("div",{children:[(0,d.jsxs)("h1",{children:["Would you like to adopt ",c,"?"]}),(0,d.jsxs)("div",{className:"buttons",children:[(0,d.jsx)("button",{onClick:this.adopt,children:"Yes"}),(0,d.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const c=(0,s.withRouter)(l),u=()=>(0,d.jsx)(i.default,{children:(0,d.jsx)(c,{})});var h=u;exports.default=h;
},{"../contexts/ThemeContext":"AHCv","../components/ErrorBoundary":"izif","../components/Carousel":"q7Av","../components/Modal":"SR9Y"}],"u08y":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t={};function a(a){const[s,o]=(0,e.useState)([]),[r,n]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?o(t[a]):async function(){o([]),n("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],o(t[a]),n("loaded")}():o([])},[a]),[s,r]}var s=a;exports.default=s;
},{}],"ys7c":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:l})=>{let c="http://pets-images.dev-apis.com/pets/none.jpg";return a.length&&(c=a[0]),(0,s.jsxs)(e.Link,{to:`/details/${l}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:c,alt:r})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsxs)("h2",{children:[t," - ",i," - ",n]})]})]})};var t=r;exports.default=t;
},{}],"eK6O":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=r(require("./Pet")),t=require("react/jsx-runtime");function r(e){return e&&e.__esModule?e:{default:e}}function a({pets:r}){return(0,t.jsx)("div",{className:"search",children:r.length?r.map(r=>(0,t.jsx)(e.default,{name:r.name,animal:r.animal,breed:r.breed,images:r.images,location:`${r.city}, ${r.state}`,id:r.id},r.id)):(0,t.jsx)("h2",{children:"No pets found"})})}var i=a;exports.default=i;
},{"./Pet":"ys7c"}],"zsGP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=r(require("../contexts/ThemeContext")),a=r(require("../hooks/useBreedList")),l=r(require("./Results")),n=require("react/jsx-runtime");function r(e){return e&&e.__esModule?e:{default:e}}const o=["bird","cat","dog","rabbit","reptile"],s=()=>{const[r,s]=(0,e.useContext)(t.default),[i,u]=(0,e.useState)(""),[c,d]=(0,e.useState)(""),[h,p]=(0,e.useState)(""),[x,j]=(0,e.useState)([]),[v]=(0,a.default)(c);async function m(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${c}&location=${i}&breed=${h}`),t=await e.json();j(t.pets)}(0,e.useEffect)(()=>{m()},[]);const b=e=>d(e.target.value),f=e=>p(e.target.value),g=e=>s(e.target.value);return(0,n.jsxs)("div",{className:"search-params",children:[(0,n.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,n.jsxs)("label",{htmlFor:"location",children:["Location",(0,n.jsx)("input",{id:"location",placeholder:"location",value:i,onChange:e=>u(e.target.value)})]}),(0,n.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,n.jsxs)("select",{id:"animal",value:c,onChange:b,onBlur:b,children:[(0,n.jsx)("option",{}),o.map(e=>(0,n.jsx)("option",{value:e,children:e},e))]})]}),(0,n.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,n.jsxs)("select",{id:"breed",value:h,onChange:f,onBlur:f,children:[(0,n.jsx)("option",{}),v.map(e=>(0,n.jsx)("option",{value:e,children:e},e))]})]}),(0,n.jsxs)("label",{htmlFor:"theme",children:["Theme",(0,n.jsxs)("select",{value:r,id:"theme",onChange:g,onBlur:g,children:[(0,n.jsx)("option",{}),(0,n.jsx)("option",{value:"red",children:"red"}),(0,n.jsx)("option",{value:"pink",children:"pink"}),(0,n.jsx)("option",{value:"green",children:"green"}),(0,n.jsx)("option",{value:"orange",children:"orange"})]})]}),(0,n.jsx)("button",{style:{backgroundColor:r},children:"Submit"})]}),(0,n.jsx)(l.default,{pets:x})]})};var i=s;exports.default=i;
},{"../contexts/ThemeContext":"AHCv","../hooks/useBreedList":"u08y","./Results":"eK6O"}],"FHab":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("../contexts/ThemeContext")),s=u(require("./Details")),d=u(require("../components/SearchParams")),i=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("darkblue");return(0,i.jsx)(e.StrictMode,{children:(0,i.jsx)(t.default.Provider,{value:u,children:(0,i.jsxs)("div",{children:[(0,i.jsx)("header",{children:(0,i.jsx)(r.Link,{to:"/",children:(0,i.jsx)("h1",{children:"Adopt me!"})})}),(0,i.jsxs)(r.Switch,{children:[(0,i.jsx)(r.Route,{path:"/details/:id",children:(0,i.jsx)(s.default,{})}),(0,i.jsx)(r.Route,{path:"/",children:(0,i.jsx)(d.default,{})})]})]})})})};var c=a;exports.default=c;
},{"../contexts/ThemeContext":"AHCv","./Details":"5I+D","../components/SearchParams":"zsGP"}],"Focm":[function(require,module,exports) {
"use strict";var e=u(require("express")),t=require("react-dom/server"),r=require("react-router-dom"),s=u(require("fs")),i=u(require("../src/pages/App")),n=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const o=process.env.port||3e3,d=s.default.readFileSync("dist/index.html").toString(),l=d.split("Not rendered"),a=(0,e.default)();a.use("/dist",e.default.static("dist")).use((e,s)=>{s.write(l[0]);const u={},o=(0,n.jsx)(r.StaticRouter,{url:e.url,context:u,children:(0,n.jsx)(i.default,{})}),d=(0,t.renderToNodeStream)(o);d.pipe(s,{end:!1}),d.on("end",()=>{s.status(u||200),s.write(l[1]),s.end()})}),console.log(`Listening on http://localhost:${o}`),a.listen(o);
},{"../src/pages/App":"FHab"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map